import { motion, useReducedMotion } from 'motion/react';

const sections = [
  {
    title: 'Information we collect',
    content: (
      <>
        <p>
          When you join the Photon waitlist, we collect the email address you
          provide.
        </p>
        <p>
          We may also receive limited technical information necessary to operate
          and secure the website, such as request and server information
          generated by our hosting infrastructure.
        </p>
        <p>
          We do not intentionally collect sensitive personal information through
          the Photon waitlist.
        </p>
      </>
    ),
  },
  {
    title: 'How we use your information',
    content: (
      <>
        <p>
          We use your email address to add you to and manage your place on the
          Photon waitlist, contact you about Photon availability, releases,
          early access, and related project updates, and protect the waitlist
          from abuse.
        </p>
        <p>We do not sell your personal information.</p>
      </>
    ),
  },
  {
    title: 'Lawful basis',
    content: (
      <>
        <p>
          We process your email address because you have asked to join the
          Photon waitlist and receive Photon-related updates.
        </p>
        <p>
          Where our processing relies on your consent, you may withdraw that
          consent at any time by contacting us.
        </p>
      </>
    ),
  },
  {
    title: 'Who we share information with',
    content: (
      <>
        <p>
          We use service providers to operate the Photon website and waitlist.
          Supabase stores waitlist information. Our website hosting and email
          delivery providers may also process information where necessary to
          provide their services.
        </p>
        <p>
          We do not share your email address with third parties for their own
          advertising purposes.
        </p>
      </>
    ),
  },
  {
    title: 'International data transfers',
    content: (
      <p>
        Some service providers used by Photon may process information outside
        the United Kingdom. Where applicable, we rely on appropriate safeguards
        required by data protection law for international transfers.
      </p>
    ),
  },
  {
    title: 'How long we keep your information',
    content: (
      <>
        <p>
          We keep your email address for as long as necessary to operate the
          Photon waitlist and provide the updates you requested. We will delete
          or anonymise information when it is no longer required for those
          purposes.
        </p>
        <p>You can request removal from the waitlist at any time.</p>
      </>
    ),
  },
  {
    title: 'Your rights',
    content: (
      <>
        <p>
          Depending on the circumstances, UK data protection law may give you
          the right to request access to or correction or deletion of your
          personal information; restrict or object to certain uses; request
          transfer of certain information; and withdraw consent where we rely on
          consent.
        </p>
        <p>
          To exercise these rights, contact us using the details below. You also
          have the right to raise a concern with the UK Information
          Commissioner’s Office (ICO).
        </p>
      </>
    ),
  },
  {
    title: 'Cookies and analytics',
    content: (
      <p>
        Photon does not use your waitlist email address for advertising or
        cross-site tracking. If we introduce analytics, cookies, or other
        tracking technologies in the future, this policy will be updated to
        explain their use and any consent requirements that apply.
      </p>
    ),
  },
  {
    title: 'Changes to this policy',
    content: (
      <p>
        We may update this Privacy Policy when the Photon website, waitlist, or
        the services we use change. The date at the top of this page indicates
        when the policy was last updated.
      </p>
    ),
  },
];

export function PrivacyPolicyPage() {
  const shouldReduceMotion = useReducedMotion();

  return (
    <motion.article
      initial={shouldReduceMotion ? false : { opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={
        shouldReduceMotion
          ? { duration: 0 }
          : { duration: 0.45, ease: 'easeOut' }
      }
      className="max-h-[calc(100svh-10rem)] w-full max-w-2xl overflow-y-auto rounded-2xl border border-white/15 bg-black/20 px-5 py-6 text-left text-on-overlay shadow-xl shadow-black/10 backdrop-blur-md sm:px-8 sm:py-8"
    >
      <h1 className="mt-2 font-heading text-3xl font-normal tracking-tight sm:text-4xl">
        Privacy Policy
      </h1>
      <p className="mt-2 text-sm text-on-overlay/65">
        Last updated: 4 October 2026
      </p>
      <div className="mt-6 space-y-6 text-sm leading-relaxed text-on-overlay/85 sm:text-base">
        <p>
          Photon Browser (“Photon”, “we”, “us”) respects your privacy. This
          policy explains what information we collect through the Photon website
          and waitlist, why we collect it, and how it is handled.
        </p>
        {sections.map(({ title, content }) => (
          <section key={title} className="space-y-2">
            <h2 className="font-heading text-lg font-medium text-on-overlay">
              {title}
            </h2>
            <div className="space-y-2">{content}</div>
          </section>
        ))}
        <section className="space-y-2">
          <h2 className="font-heading text-lg font-medium text-on-overlay">
            Contact
          </h2>
          <p>
            For privacy questions, requests, or requests to remove your email
            from the waitlist, email{' '}
            <a
              href="mailto:[YOUR PRIVACY/CONTACT EMAIL]"
              className="underline decoration-on-overlay/50 underline-offset-4 hover:decoration-on-overlay"
            >
              [YOUR PRIVACY/CONTACT EMAIL]
            </a>
            .
          </p>
        </section>
      </div>
      <a
        href="/"
        className="pressable mt-7 inline-flex rounded-[12px] border border-white/30 bg-white/15 px-5 py-2.5 text-sm text-white transition-colors hover:bg-white/25 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white"
      >
        Back to home
      </a>
    </motion.article>
  );
}
